export const PROCEDURES = [
  "Consulta Inicial",
  "Retorno",
  "Abdominoplastia",
  "Artroscopia no Joelho",
  "Blefaroplastia",
  "Cirurgia bariátrica",
  "Cirurgia da Fimose",
  "Cirurgia de Laqueadura",
  "Cirurgia de Mão",
  "Cirurgia de Varizes",
  "Cirurgia Dermatológica",
  "Cirurgia Otorrinolaringológica",
  "Endometriose por Laparoscopia",
  "Fertilização In Vitro (FIV)",
  "Hérnia Abdominal",
  "Hidrocelectomia",
  "Histerectomia",
  "Histeroscopia",
  "Implante Capilar",
  "Laparoscopia Ginecológica",
  "Lipo HD",
  "Lipoaspiração",
  "Mamoplastia",
  "Nutricionista",
  "Orquiectomia",
  "Otoplastia",
  "Plástica nos Seios",
  "Prótese Peniana",
  "Rinoplastia",
  "Vasectomia",
  "Outro",
];
