name: Auto Comment on PR

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Adicionar comentário no PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          TEMPLATE=$(cat .github/PULL_REQUEST_TEMPLATE/pull_request_template.md)
          
          MENSAGEM="Por favor, preencha a descrição do PR usando o template abaixo:
          
          \`\`\`
          $TEMPLATE
          \`\`\`"
          
          gh pr comment $PR_URL --body "$MENSAGEM"
